#!/bin/bash
sudo rm files/OutputImage2.txt
sudo apt-get install python3
sudo apt-get install python3-numpy
sudo python3 -m pip install -U pip
sudo python3 -m pip install -U matplotlib
sudo python3 Testdecoder2.py
python3 display.py